language: python
python:
- '2.7'
- '3.4'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: JcPGzsFxk4V6OZ+VUZnjPc283T1GeAGlp1a1Ru/5fnddYeqLvInCJQGhSUr2qzs5p982spW7a3KE18JmhV704/pe1yFAdbAPxVw00VjQcCTdUv6vpnRfIcadY9ihDke1OOoCOMnT5REfcCJo7HCX+AhISj2kLjnvkNsuIWlej7122WkTC+jFOw7Q+6G1zGXi8JjBRY4jHsXRIQbgj82GvC9gwFKnk/9zewivZskU1K5ViC0d/g+trq/yj72EDLgCaOyonr9+eE36AeVf5CmMGrT5a+7to/6ry2OWAtk1M+bUbCJgm2Skmu97RQVo3F4mKakdoA/4bRoF3dxfzPbRnM176ZtpxLwuGnFBxGE1Z7BShGYybtkYdBk4IQdjUNYwfHLh3H56nOXC+3HcpOQsI0vyDuMYuWqV89cbTwzm4e8AU+gJ4B+Qc6zRyrBlUT0bM9eckIicrSGG0yVMA9DDr1i1HgF/dmzVrPcvpgIlGtCNFGeEFKme6M9cqvd2+oNWPvK2MU4oNAZ80uhdVBp7n1K6xQYydrD3mWr7+kkq9jMxWLjWTOYBDkmPFlFzrUvCSbkLOTxVttJbthF8Lys0A/j/T7qjnDep1/osu5AH7iNYkV6pDczv1B+bSroA5yMXl0Emeu1rn/gWxMcFgAbrtjoErSI0pm4nJALL8ZkRGD0=
  app: ac41004-team-2
  on:
    repo: jslvtr/AC41004-Team-2
notifications:
  slack:
    secure: VZm8OahAdvvwurqXrCtFZvXyZWywiyaYdl80ApQdimo4gC670UXo3inViXGTn7pMVgI/xoBm8Z8Cn2PZErMEGmEFimtFbgHldh+d9tj2d7IK5Vk8QXEGKMCG7G81t3woHqqcAwmzKk8Mn5DNkVN3vozVU5iwGQhGnAHWnTk7BVDvpemEgiOWe+UerFXUOZJyI9j8TArESBKCGbA+0IAWwN8ncuJuXza+b2RbQcDqqA52qvf+mQprqJOvHvLUFb0QqgA2uP0HuMh2a7ys5cmrwTEPPatmg55yM6NPrMuYs6FL+Y9/2MOZaAo7M7N45+revRbomwNvmiBrf6oJGmxX1lTetovK9Hma2OEzXqpDRTgj1WISXu8g3O64zX0eN7gq/CT8BGCCDMuwhdlmOlqe401CHB220kMBlsYi05Vaq9c09lRunF0sklHDrtFCM1fD7zZZmXeDJWTBwCHAGP7CMCVW25Lf5fyDlnd+lbSjQ0uA/4eF1/C0zpA7Ey93rOSFESSxXnVrlXipVwI9G9YK5B8uza/L3E1YuT4Uo6eUWMvdhI4dck7Jnw7PixdWtixd4r8nfVQtI0dWeDg0ZFvlQUj2kwjQjS1LGHl8J012qUDqbdKvg+bOpbZpe+LEtne5KZ3GFkIipJNLfj1R1q0O0eQy2Pxk5DJh44iq+EeCEbQ=
branches:
  only:
    - master